apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
    name: service-per-pod
spec:
    resources:
        - apiVersion: app/v1beta1
          resource: statefulsets
          annotationSelector:
              matchExpressions:
                  - { key: service-per-pod-label, operator: Exists }
                  - { key: service-per-pod-ports, operator: Exists }
              attachments:
                  -   apiVersion: v1
                      resource: services
              hooks:
                  sync:
                      webhook:
                          url: http://service-per-pod.metacontroller/sync-service-per-pod
                          timeout: 10s