apiVersion: v1
kind: Service
metadata:
    name: minecraft-server-service
    labels:
        app: minecraft-server-service
spec:
    type: NodePort
    ports:
        -   port: 25565
            name: default
    selector:
        app: minecraft-server-service
