apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
    name: "minecraft-simple"
spec:
    # if there is more than one container, specify which one is the game server
    # Array of ports that can be exposed as direct connections to the game server container
    ports:
        # name is a descriptive name for the port
        - name: default
            # portPolicy has three options:
            # - "Static", user defines the hostPort that the game client will connect to. Then onus is on the user to ensure that the
            # port is available. When static is the policy specified, `hostPort` is required to be populated
          portPolicy: Static
            # [Stage:Beta]
            # [FeatureFlag:ContainerPortAllocation]
            # The name of the container to open the port on. Defaults to the game server container if omitted or empty.
          container: minecraft
            # the port that is being opened on the game server process
          containerPort: 25565
            # the port exposed on the host, only required when `portPolicy` is "Static". Overwritten when portPolicy is "Dynamic".
          hostPort: 25565
            # protocol being used. Defaults to UDP. TCP and TCPUDP are other options
            # - "UDP" (default) use the UDP protocol
            # - "TCP", use the TCP protocol
            # - "TCPUDP", uses both TCP and UDP, and exposes the same hostPort for both protocols.
            #       This will mean that it adds an extra port, and the first port is set to TCP, and second port set to UDP
          protocol: TCP
    # [Stage:Alpha]
    # [FeatureFlag:PlayerTracking]
    # Players provides the configuration for player tracking features.
    # Commented out since Alpha, and disabled by default
    # players:
    #   # set this GameServer's initial player capacity
    #   initialCapacity: 10
    # Pod template configuration
    # https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#podtemplate-v1-core
    template:
        # Pod Specification
        spec:
            containers:
                - name: minecraft
                  image:  itzg/minecraft-server
                  imagePullPolicy: Always